default: &default
  twitter_consumer_key: 'wgPe8Apw2Wl8qK5iXlEWpE2X1'
  twitter_consumer_secret: '	lISCyc40b2HeGKXCGJciyAjPlBYljRUQaBoCUQCt1d3WY2RqLq'
 
development:
  <<: *default
  secret_key_base: **
 
test:
  <<: *default
  secret_key_base: **
 
# Do not keep production secrets in the repository,
# instead read values from the environment.
 
## 本番環境では下記のように読み込むことで、あなたのconsumer_keyとかを悪用されませんよ、という書き方(らしい) ##
production:
  twitter_consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>