default: &default
  twitter_consumer_key: 'wgPe8Apw2Wl8qK5iXlEWpE2X1'
  twitter_consumer_secret: 'lISCyc40b2HeGKXCGJciyAjPlBYljRUQaBoCUQCt1d3WY2RqLq'
 
development:
  <<: *default
  secret_key_base: '66d73f2156e053639cf3cc02601c8be32b8e5b791ae567e992fa3005f9bba8a8acb059924e73f92a6c213305e22a09059ef9facd8be2350c521d432448b982f5'

test:
  <<: *default
  secret_key_base: '66d73f2156e053639cf3cc02601c8be32b8e5b791ae567e992fa3005f9bba8a8acb059924e73f92a6c213305e22a09059ef9facd8be2350c521d432448b982f5'

# Do not keep production secrets in the repository,
# instead read values from the environment.

## 本番環境では下記のように読み込むことで、あなたのconsumer_keyとかを悪用されませんよ、という書き方(らしい) ##
production:
  twitter_consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
